"""add_notify_clients_to_google_calendar_tokens

Revision ID: f5b5bdc7a7c2
Revises: 74858d29f6e5
Create Date: 2025-10-29 14:28:40.773124

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f5b5bdc7a7c2'
down_revision: str | Sequence[str] | None = '74858d29f6e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_calendar_tokens', sa.Column('notify_clients', sa.Boolean(), server_default='false', nullable=False, comment='Send Google Calendar invitations to clients (requires client email)'))
    op.alter_column('google_calendar_tokens', 'last_sync_error',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_comment='Error message from the last failed sync operation',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_calendar_tokens', 'last_sync_error',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_comment='Error message from the last failed sync operation',
               existing_nullable=True)
    op.drop_column('google_calendar_tokens', 'notify_clients')
    # ### end Alembic commands ###
