name: 'Setup Python with uv'
description: 'Install Python 3.13.5 with uv package manager and caching'
inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.13.5'
  uv-version:
    description: 'UV package manager version'
    required: false
    default: 'latest'
  working-directory:
    description: 'Working directory for caching'
    required: false
    default: './backend'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: ${{ inputs.uv-version }}

    - name: Set up Python ${{ inputs.python-version }}
      shell: bash
      run: |
        uv python install ${{ inputs.python-version }}
        uv python pin ${{ inputs.python-version }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          ${{ inputs.working-directory }}/.venv
        key: ${{ runner.os }}-uv-${{ hashFiles(format('{0}/pyproject.toml', inputs.working-directory), format('{0}/uv.lock', inputs.working-directory)) }}
        restore-keys: |
          ${{ runner.os }}-uv-
