name: 'Setup Docker Buildx'
description: 'Setup Docker Buildx with BuildKit for multi-platform builds'
inputs:
  buildx-version:
    description: 'Docker Buildx version'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=moby/buildkit:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
