# Generated by Django 3.2.11 on 2022-01-21 11:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם')),
                ('age', models.IntegerField(verbose_name='גיל')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IL', verbose_name='מספר טלפון')),
                ('address', models.CharField(max_length=255, verbose_name='כתובת')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='תיאור')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='treatments', to='client_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='תיאור')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record_patient', to='client_app.client', verbose_name='מטופל')),
            ],
        ),
    ]
