# Generated by Django 4.0.4 on 2022-04-20 12:51

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם')),
                ('age', models.IntegerField(verbose_name='גיל')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IL', verbose_name='מספר טלפון')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')])),
                ('address', models.CharField(max_length=255, verbose_name='כתובת')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='תיאור הבעיה')),
                ('process', models.TextField(blank=True, verbose_name='הטיפול הניתן')),
                ('notice', models.TextField(blank=True, verbose_name='הערות')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='treatments', to='client_app.client')),
            ],
            options={
                'ordering': ('modified',),
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='תיאור')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record_patient', to='client_app.client', verbose_name='מטופל')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(verbose_name='תאריך')),
                ('done', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='client_app.client', verbose_name='מטופל')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='client_app.treatment')),
            ],
        ),
    ]
